### ISSUE TITLE
ERROR: In file 'bwdata/docker/docker-compose.yml', the service name 404 must be a quoted string, i.e. '404'.

### ISSUE THREAD

**Issue by gregf** [bitwarden/core#129]
My docker-compose.yml has Invalid URL 404 in it when trying to run `bitwarden.sh update` after adding my mailgun login to globals.env.

**Comment by kspearrin** [comment]
Sounds like you forgot to `updateself` first.

https://help.bitwarden.com/article/updating-on-premise/

**Comment by gregf** [comment]
same error

**Comment by gregf** [comment]
```
cat bwdata/docker/docker-compose.yml 
404: Not Found

```

**Comment by kspearrin** [comment]
Did you run `update` now? `update` is suppose to rebuild a new `bwdata/docker/docker-compose.yml `

**Comment by gregf** [comment]
I ran `./bitwarden.sh updateself` then `./bitwarden.sh update`. The update command is what is giving me the 404 error.

**Comment by gregf** [comment]
This is the output of `bash -x ./bitwarden.sh update`

```
+ docker --version
Docker version 17.09.0-ce, build afdb6d4
+ docker-compose --version
docker-compose version 1.17.0, build ac53b73
+ echo ''

+++ dirname ./bitwarden.sh
++ cd .
++ pwd
+ DIR=/home/toor
++ basename ./bitwarden.sh
+ SCRIPT_NAME=bitwarden.sh
+ SCRIPT_PATH=/home/toor/bitwarden.sh
+ OUTPUT=/home/toor/bwdata
+ '[' 1 -eq 2 ']'
+ SCRIPTS_DIR=/home/toor/bwdata/scripts
+ GITHUB_BASE_URL=https://raw.githubusercontent.com/bitwarden/core/master
+ COREVERSION=1.14.0
+ WEBVERSION=1.20.0
+ '[' update == install ']'
+ '[' update == start -o update == restart ']'
+ '[' update == update ']'
+ checkOutputDirExists
+ '[' '!' -d /home/toor/bwdata ']'
+ downloadRunFile
+ '[' '!' -d /home/toor/bwdata/scripts ']'
+ curl -s -o /home/toor/bwdata/scripts/run.sh https://raw.githubusercontent.com/bitwarden/core/master/scripts/run.sh
+ chmod u+x /home/toor/bwdata/scripts/run.sh
+ /home/toor/bwdata/scripts/run.sh update /home/toor/bwdata 1.14.0 1.20.0
ERROR: In file '/home/toor/bwdata/docker/docker-compose.yml', the service name 404 must be a quoted string, i.e. '404'.
```

**Comment by kspearrin** [comment]
Can you paste the contents of `./bitwarden.sh` and `./bwdata/scripts/update.sh`?

**Comment by kspearrin** [comment]
Sorry, meant `./bwdata/scripts/run.sh`

**Comment by gregf** [comment]
bitwarden.sh

[bitwarden.txt](https://github.com/bitwarden/core/files/1464333/bitwarden.txt)

./bwdata/scripts/run.sh

[run.txt](https://github.com/bitwarden/core/files/1464334/run.txt)

**Comment by gregf** [comment]
Had to rename them to .txt to upload them

**Comment by kspearrin** [comment]
Ok, I see what happened now. By running the old updater first you deleted the file that is now trying to be run by run.sh (it assumes it wasn't deleted).

Re-create a new ./bwdata/docker/docker-compose.yml with:

```
version: '3'

services:
  mssql:
    image: bitwarden/mssql:1.14.0
    container_name: mssql
    restart: always
    volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../mssql/backups:/etc/bitwarden/mssql/backups
    env_file:
      - mssql.env
      - ../env/mssql.override.env

  web:
    image: bitwarden/web:1.20.0
    container_name: web
    restart: always
    volumes:
      - ../web:/etc/bitwarden/web

  attachments:
    image: bitwarden/attachments:1.14.0
    container_name: attachments
    restart: always
    volumes:
      - ../core/attachments:/etc/bitwarden/core/attachments

  api:
    image: bitwarden/api:1.14.0
    container_name: api
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
    env_file:
      - global.env
      - ../env/global.override.env

  identity:
    image: bitwarden/identity:1.14.0
    container_name: identity
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
    env_file:
      - global.env
      - ../env/global.override.env

  icons:
    image: bitwarden/icons:1.14.0
    container_name: icons
    restart: always

  nginx:
    image: bitwarden/nginx:1.14.0
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl
```

You probably need to change `1.14.0` to whatever the current version you are running is `1.13.1` maybe?

Then run the `update` command again.
