### ISSUE TITLE
Implementation of existing nginx

### ISSUE THREAD

**Issue by KonstGIT** [bitwarden/core#188]
I am very new to the selfhosted world and I am just starting working with docker.

**Situation**:
Several subdomains are managed by a nginx reverse proxy. That listens to 80 and 443. Behind this proxy I want to install bitwarden. The subdomain will be vault.myhosting.xx.

**What I did:**
First I installed bitwarden via ./bitwarden install. This worked until the nginx container was started and caused a conflict with the existing nginx. I then adjusted bwdata/docker/docker-compose.yml and and changed it to:

```
version: '3'

services:
  mssql:
    image: bitwarden/mssql:1.16.0
    container_name: bitwarden-mssql
    restart: always
    volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../mssql/backups:/etc/bitwarden/mssql/backups
    env_file:
      - mssql.env
      - ../env/mssql.override.env

  web:
    image: bitwarden/web:1.22.0
    container_name: bitwarden-web
    restart: always
    volumes:
      - ../web:/etc/bitwarden/web
    **environment:
      VIRTUAL_HOST: vault.myhosting.xx**

  attachments:
    image: bitwarden/attachments:1.16.0
    container_name: bitwarden-attachments
    restart: always
    volumes:
      - ../core/attachments:/etc/bitwarden/core/attachments

  api:
    image: bitwarden/api:1.16.0
    container_name: bitwarden-api
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
    env_file:
      - global.env
      - ../env/global.override.env

  identity:
    image: bitwarden/identity:1.16.0
    container_name: bitwarden-identity
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
    env_file:
      - global.env
      - ../env/global.override.env

  icons:
    image: bitwarden/icons:1.16.0
    container_name: bitwarden-icons
    restart: always

**networks:
  default:
    external:
      name: router_default**
```
router_default is the network of my nginx reverse proxy. After that I was able to access bitwarden with my browser. 

**Problem:**
Unfortunatly "An unexpected error has occured" is displayed when I try to setup a new user. I think there is something wrong with the communication between the mssql and web. 

Thank you for your help!
