### ISSUE TITLE
Self-hosted: unable to use non-default network

### ISSUE THREAD

**Issue by itsthejb** [bitwarden/core#347]
Hi there,

I wanted to respond to the following discussion: https://community.bitwarden.com/t/possibility-to-use-existing-docker-bridges/1963, but I couldn't sign up to the forum due to the following error:

> New registrations are not allowed from your IP address (maximum limit reached). Contact a staff member.

Perhaps that's an issue? In any case, I wanted to do as the discussion, and name a network, rather than using the default `docker_default`. Therefore, I created the following `docker-compose.override.yml`:

```
version: '3'

services:
  mssql:
    network_mode: bridge
  web:
    network_mode: bridge
  attachments:
    network_mode: bridge
  api:
    network_mode: bridge
  identity:
    network_mode: bridge
  admin:
    network_mode: bridge
  icons:
    network_mode: bridge
  notifications:
    network_mode: bridge
  nginx:
    network_mode: bridge
```

However, I couldn't get it to work: the startup gets stuck in a loop with the following:

> 2018/08/29 19:52:42 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:16

I also tried to create a network `docker create bitwarden`, and use the following file:

```
version: '3'

services:
  mssql:
    network_mode: bitwarden
  web:
    network_mode: bitwarden
  attachments:
    network_mode: bitwarden
  api:
    network_mode: bitwarden
  identity:
    network_mode: bitwarden
  admin:
    network_mode: bitwarden
  icons:
    network_mode: bitwarden
  notifications:
    network_mode: bitwarden
  nginx:
    network_mode: bitwarden
```

But the same problem. Can anyone help? Thanks in advance
