### ISSUE TITLE
Verify Email never gets sent from container

### ISSUE THREAD

**Issue by perfecto25** [bitwarden/core#364]
running on centos 7 VM, BW is setup and running, 

when I login as admin, I click on Verify Email > send email, get a green box saying email was sent, but I never receive it

I checked my docker host maillog, no acitivity, 
nothing in Notifications
```
[root@saltdev1 logs]# tree
.
├── admin
├── api
│   └── Api
│       └── 20180926.txt
├── icons
├── identity
├── mssql
│   ├── errorlog
│   ├── errorlog.1
│   ├── errorlog.2
│   ├── HkEngineEventFile_0_131824475414340000.xel
│   ├── HkEngineEventFile_0_131824481856230000.xel
│   ├── log_1.trc
│   ├── log_2.trc
│   ├── log_3.trc
│   ├── log.trc
│   ├── sqlagentstartup.log
│   ├── system_health_0_131824475422220000.xel
│   └── system_health_0_131824481862880000.xel
├── nginx
│   ├── access.log
│   └── error.log
└── notifications
```

the issue isnt w my testbox postfix, I can successfully send a test msg from it, 
```
[root@saltdev1 logs]# mail -s "Test Subject" mr@xxx.com < /dev/null
Null message body; hope that's ok

tail -f /var/log/maillog

Sep 26 11:17:31 saltdev1 postfix/qmgr[1531]: 43DFC1334B42: from=<root@saltdev1.localdomain>, size=473, nrcpt=1 (queue active)
Sep 26 11:17:31 saltdev1 postfix/smtp[10398]: 43DFC1334B42: to=<mr@xxx.com>, relay=aspmx.l.google.com[172.217.197.27]:25, delay=0.35, delays=0.03/0.01/0.16/0.14, dsn=2.0.0, status=sent (250 2.0.0 OK 1537975051 r2-v6si2915457qtr.185 - gsmtp)
Sep 26 11:17:31 saltdev1 postfix/qmgr[1531]: 43DFC1334B42: removed
```

I can verify Im getting this email in my gmail inbox,

is there a way to troubleshoot BW mail ?

Thanks

**Comment by kspearrin** [comment]
Are there any errors in the api logs at ./bwdata/logs?

**Comment by perfecto25** [comment]
nothing in api log, 

2018-09-26 16:00:00.062 +00:00 [Information] Starting job "AliveJob" at 09/26/2018 16:00:00.
2018-09-26 16:00:00.098 +00:00 [Information] It's alive!
2018-09-26 16:00:00.105 +00:00 [Information] Finished job "AliveJob" at 09/26/2018 16:00:00.

**Comment by perfecto25** [comment]
this is my compose file, i added hostname to API section, 


```
version: '3'

services:
  mssql:
    image: bitwarden/mssql:1.24.0
    container_name: bitwarden-mssql
    restart: always
    volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../logs/mssql:/var/opt/mssql/log
      - ../mssql/backups:/etc/bitwarden/mssql/backups
    env_file:
      - mssql.env
      - ../env/uid.env
      - ../env/mssql.override.env

  web:
    image: bitwarden/web:2.3.0
    container_name: bitwarden-web
    restart: always
    volumes:
      - ../web:/etc/bitwarden/web
    env_file:
      - global.env
      - ../env/uid.env

  attachments:
    image: bitwarden/attachments:1.24.0
    container_name: bitwarden-attachments
    restart: always
    volumes:
      - ../core/attachments:/etc/bitwarden/core/attachments
    env_file:
      - global.env
      - ../env/uid.env

  api:
    image: bitwarden/api:1.24.0
    container_name: bitwarden-api
    hostname: saltdev1.quantitativebrokers.com
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/api:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  identity:
    image: bitwarden/identity:1.24.0
    container_name: bitwarden-identity
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/identity:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  admin:
    image: bitwarden/admin:1.24.0
    container_name: bitwarden-admin
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/admin:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  icons:
    image: bitwarden/icons:1.24.0
    container_name: bitwarden-icons
    restart: always
    volumes:
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/icons:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env

  notifications:
    image: bitwarden/notifications:1.24.0
    container_name: bitwarden-notifications
    restart: always
    volumes:
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/notifications:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  nginx:
    image: bitwarden/nginx:1.24.0
    container_name: bitwarden-nginx
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl
      - ../logs/nginx:/var/log/nginx
    env_file:
      - ../env/uid.env

```
