### ISSUE TITLE
Timezone in container does not match host

### ISSUE THREAD

**Issue by maklass** [bitwarden/core#407]
I was trying to configure Fail2Ban for Bitwarden and noticed that the timezone in the nginx access logs doesn't match the timezone on the host machine.  
I was able to solve this by setting a `TZ` environment variable in my `docker-compose.override.yml` like this  
```
services:
    nginx:
        environment:
            - TZ=Europe/Berlin
```
but maybe it should be set to the host timezone by default.
